JuliaDebug/SnoopCompile.jl

- src/SnoopCompile.jl
This doesn't check to make sure people are in a source checkout, I was too lazy.
> For those that don't have JULIAHOME defined, autogenerate it!

- .travis.yml
- src/SnoopCompile.jl
- test/REQUIRE
- test/colortypes.jl
- test/runtests.jl
Fixes #5 and https://github.com/JuliaLang/julia/issues/15101#issuecomment-197731876 if you use julia-0.5.
> Support julia-0.5 (don't need compiler modifications) and binary installs

- .travis.yml
- README.md
- REQUIRE
- appveyor.yml
- examples/gadfly.jl
- examples/images.jl
- src/SnoopCompile.jl
- test/REQUIRE
- test/colortypes.jl
- test/runtests.jl
> More 0.7/1.0 fixes

- README.md
- examples/gadfly.jl
- examples/images.jl
- src/SnoopCompile.jl
- test/colortypes.jl
- test/runtests.jl
The new feature works on julia v"1.2.0-DEV.564" or higher.
> Add the ability to snoop on inference

- src/SnoopCompile.jl
- test/runtests.jl
There's no reason the old one shouldn't have worked, but whatever...
> Get the docstring for snoopi working

- README.md
@timholy If you like, you can merge this for a full real-world example for using SnoopCompile
> Adding a full real-world example

- README.md
> Updating MatLang link

- .gitignore
- Project.toml
- src/SnoopCompile.jl
- src/parcel_snoopi.jl
- src/write.jl
This also fixes a problem with module assignment.
> Sort the precompile directives

- Project.toml
- docs/src/bot.md
- src/bot.jl
- src/bot/precompileInclude.jl
- src/bot/snoopi_bench.jl
- test/bot/bot.jl
Should fix https://github.com/timholy/SnoopCompile.jl/issues/67
> Fix depcrecation error

- src/parcel_snoopi.jl
- test/snoopi.jl
> Remove duplicates from `parcel` (fixes #70)

- Project.toml
- src/snoopi.jl
The new AbstractInterpreter framework broke this package, but it's a pretty easy fix.
> Support AbstractInterpreter

- docs/src/snoopc.md
> Fix macro name

- Project.toml
Submitted as a PR just to make sure all the CI works properly.
> Version 1.5

- docs/src/snoopr.md
- examples/invalidations_blog.jl
- src/invalidations.jl
- test/snoopr.jl
> Invalidation show

- src/bot/deprecations.jl
Like with #93, I think we need these?
> Add funcname to Base.depwarn calls

- .github/workflows/TagBot.yml
Found in https://github.com/JuliaDocs/Documenter.jl/issues/1277#issuecomment-612701975
> Fix TagBot so it can produce docs for releases

- Project.toml
- SnoopCompileAnalysis/Project.toml
- SnoopCompileBot/Project.toml
- SnoopCompileCore/Project.toml
Hopefully the docs-build is working now, so this release is solely to generate them for 1.7.x.
> Version 1.7.1

- SnoopCompileAnalysis/src/invalidations.jl
> Skip TypeMapEntry invalidate_mt_cache entries

- docs/src/reference.md
- docs/src/snoopr.md
Nothing very fundamental here, but I do think these make it more readable.
> Improvements to snoopr docs

- docs/src/snoopr.md
This documents one of the more important "generic" tricks.
> Add docs on interfaces for abstract types

- docs/src/snoopr.md
Some invalidations were really hard to find. The new `findcaller` from MethodAnalysis improves this a lot, so advertise it here.
> Document usage of `findcaller`

- src/invalidations.jl
- test/snoopr.jl
> Invalidations: support method deletion

- src/parcel_snoopi_deep.jl
- test/snoopi_deep.jl
With more time spent playing with this, I found I wanted to to be easier to extract the Method or MethodInstance without having to worry about which exact object I'm working with or what its field names are.
Also adds `Cthulhu.descend` support for `InferenceTrigger`...since of course that's what you want to do next.
> Add a few convenience methods

- src/parcel_snoopi_deep.jl
- test/snoopi_deep.jl
The changes to `edit` are important but I am not sure how to test them.
> More ergonomics & cleanups

- src/parcel_snoopi_deep.jl
- test/snoopi_deep.jl
> Switch from pairs to tuples in flatten_times

- src/parcel_snoopi_deep.jl
- test/snoopi_deep.jl
This uses red coloration to indicate non-precompilable methods.
It also changes the default rendering of the flamegraph func.
The previous default was too expensive for long traces, often
requiring more than a minute just to print all the signatures.
This seems wasteful given that the signature is already
available via the `linfo` field of the StackFrame.
To support integration with other tools, this attempts to
incorporate some of the spirit of #160, especially by allowing
`mode=:slots` (deliberately undocumented for now).
However, this should be a target for removal at some point,
as this is an abuse and there would appear to be much cleaner
solutions. (e.g., generalize the `linfo` field of StackFrame
to allow slottypes to be supplied.)
Closes #160
> Annotate flamegraph with isprecompilable

- src/parcel_snoopi.jl
- test/snoopi_deep.jl
> Handle UnionAll signatures in `add_repr!`

- src/parcel_snoopi_deep.jl
- src/visualizations.jl
This isn't heavily tested due to the atsign-require, so bugs
had crept in.
> Small fixes for PGDO

- src/parcel_snoopi_deep.jl
- src/visualizations.jl
- test/snoopi_deep.jl
There was really no solid justification for the previous test. This new
version is based on more solid footing.
> Fix a flaky runtime/inferencetime test

- README.md
Point to GitHub Actions instead of Travis.
> README.md: update build status badge

- .github/workflows/ci.yml
- README.md
Contains PR #208, thus closes #208
> Track code coverage using Codecov

- docs/src/snoopi_deep.md
- docs/src/snoopi_deep_analysis.md
- src/SnoopCompile.jl
- src/parcel_snoopi_deep.jl
- test/snoopi_deep.jl
This was a big surprise. It's quite confusing to interpret the results
if invalidations are rampant, so it's best to know about them.
> Check tinf for invalidations

- src/parcel_snoopi_deep.jl
- test/snoopi_deep.jl
> Greatly improve suggest

- src/parcel_snoopi_deep.jl
There's no good reason to try to use the function in location key.
The function type is simpler and more robust.
> Simplify location key

- src/parcel_snoopi_deep.jl
- test/snoopi_deep.jl
This seems to be the nicest way to analyze inference triggers.
TODO: rewrite the docs to use this
> Organize inference triggers by Method

- test/snoopi_deep.jl
- test/snoopr.jl
This fixes test failures that stem from more aggressive
constant-propagation on Julia nightly.
> Tests: omit const-prop numbers

- src/parcel_snoopi.jl
- test/snoopi.jl
> Handle missing kwbody parent

- docs/src/snoopr.md
> Remind people to use startup-file=no

- Project.toml
- SnoopCompileCore/src/snoopi.jl
- SnoopCompileCore/src/snoopi_deep.jl
- docs/src/snoopi.md
- src/SnoopCompile.jl
- src/parcel_snoopi_deep.jl
- src/write.jl
- test/runtests.jl
Addresses https://github.com/JuliaLang/julia/commit/c0f9666d0b94b213c7ff9e64a7b4e5268aa0e18b#commitcomment-47799292
> Introduce warnpcfail as a substitute for assert

- test/snoopi_deep.jl
The "snoopi_deep.jl" test has generated a lot of annoying output.
This makes `M` a global module in only one place, so even if the tests
are re-run in the same session, you get only one warning.
> Eliminate most module-redef warnings

- test/snoopi.jl
- test/snoopi_deep.jl
- test/snoopr.jl
*Somebody* keeps making inference better, messing up my tests. Geez! :laughing:
> Skip tests obsoleted by inference improvements

- docs/src/snoopi_deep_analysis.md
xref https://github.com/aviatesk/JET.jl/pull/315
> Add comparison to JET's dispatch analysis

- docs/src/jet.md
I already read the JET section, but wasn't sure yet what it meant. The comment at https://discourse.julialang.org/t/help-reducing-compilation-time/77823/5 helped a lot
> Add summary to JET section

- src/parcel_snoopi.jl
- test/snoopi.jl
This also resolves some issues with looking up bodyfunction names.
> Fix tests for introduction of `Core.kwcall`

- src/invalidations.jl
- test/snoopr.jl
> Fix indexing bug in `uinvalidated`

- SnoopCompileCore/Project.toml
> SnoopCompileCore 2.10.1

- .github/workflows/Documenter.yml
- .github/workflows/ci.yml
- src/parcel_snoop_inference.jl
- test/snoop_inference.jl
- fix package resolution on CI
- test `'pre'` not `'nightly'`
- fix a mac-specific test failure
- small optimization in `flatten`
> Small fixes

- test/snoop_invalidations.jl
On Julia 1.11, the impact of redefining `throw_boundserror` seems much
larger, and it breaks later tests. Defer this until the end.
> Reorder invalidation tests

- .github/workflows/ci.yml
- Project.toml
- test/extensions/cthulhu.jl
- test/runtests.jl
`ascend` is a terminal program so it takes a bit of effort to test it.
xref https://github.com/JuliaDebug/Cthulhu.jl/issues/581
> Test Cthulhu extension

- ext/SCPrettyTablesExt.jl
> Use Float16 for %

- Project.toml
- src/invalidations.jl
- test/snoop_inference.jl
> Use `join` for `backedges`

- SnoopCompileCore/src/SnoopCompileCore.jl
- SnoopCompileCore/src/snoop_invalidations.jl
- docs/src/explanations/devs.md
- src/invalidations.jl
- test/snoop_invalidations.jl
This updates to the latest nightly for invalidations.
> Simplify implementation for edge logs

- README.md
- test/snoop_inference.jl
This fixes documentation and other links
> Update README links to reflect new repository
