src/SnoopCompile.jl
test/runtests.jl

Replaces `Base.#any` with `typeof(Base.any)`.

Handle # characters in function-types (julia 0.5). Fixes #7

---

src/SnoopCompile.jl
test/runtests.jl

This seems to be another necessary julia-0.5 fix.

Omit function type as first argument on 0.5

---

.travis.yml
REQUIRE
appveyor.yml
src/SnoopCompile.jl
test/REQUIRE
test/colortypes.jl
test/runtests.jl

I haven't addressed the testing, and the package probably needs a `Project.toml` file, etc. too, but the changes here let me precompile my package successfully using `@snoop1` and include the resulting produced files with a noticeable effect on 1.0.
I ran into a number of issues related to package availability, though, trying to use `@snoop`, since the new Pkg has those projects, and people will probably typically be snooping from within a project.  So I hacked in the `using Pkg; Pkg.activate(".")`, which is definitely not the most stable solution.
Another thing is the `ccall(:jl_generating_output, Cint, ()) == 1 || return nothing` which I see from git blame has been there since the initial commit. What is the check for? On my machine, `ccall(:jl_generating_output, Cint, ())` always …

v1.0 compatibility changes

---

src/SnoopCompile.jl
test/colortypes.jl

Parse `where` signatures (fixes #20)

---

Project.toml
src/SnoopCompile.jl
test/runtests.jl

Addresses #29 
This works for the [example](https://gist.github.com/lkapelevich/e4f539e7da084240a3c49a76554eb0bc) in the issue, but I'm not sure I have implemented it in the most effective way, or what the best way to test this is. If `func` (https://github.com/timholy/SnoopCompile.jl/blob/master/src/SnoopCompile.jl#L194) looks like 
`:(getfield(mod, Symbol("##...#..")))`, we add a check `isdefined(mod, "##...#..")`.

check that functions in precompile lists are defined

---

.travis.yml
Project.toml
src/SnoopCompile.jl
test/runtests.jl

Should also get the tests passing on Travis

Tweak `anonrex`

---

README.md
src/SnoopCompile.jl
test/runtests.jl

`@snoopi` is the simpler and more useful of the two macros, and since folks seem to like automation, we should support it.
Once merged I'll turn this into version 1.0.

Automate atsign-snoopi similar to snoopc

---

src/SnoopCompile.jl

If Julia compiles the returned expression, we will "miss" the inference time because the compilation happens before we turn snooping on.
The logic [here](https://github.com/JuliaLang/julia/blob/84e839227f7762b6dfa0821247cd132cf15e3581/src/toplevel.c#L793-L815) indicates that the `ccall`s could force Julia to use the compiler, so move these inside a function.

Encapsulate ccalls to enhance interpreter usage

---

.travis.yml
appveyor.yml
src/SnoopCompile.jl
test/runtests.jl

Get kwfuncs with Core.kwftype

---

docs/src/snoopi.md
src/SnoopCompile.jl
test/E.jl
test/runtests.jl

@chriselrod, can you test to see if this fixed your test cases?

Invariant naming of generators

---

docs/src/snoopi.md

Also includes other miscellaneous doc fixes.

Docs: remove statement about sorting order

---

src/parcel_snoopi.jl
test/snoopi.jl

Fixes https://github.com/timholy/SnoopCompile.jl/issues/63

blacklist remover

---

Project.toml
docs/make.jl
docs/src/index.md
docs/src/snoopr.md
examples/invalidations_blog.jl
src/SnoopCompile.jl
src/bot/snoopi_bench.jl
src/invalidations.jl
src/parcel_snoopi.jl
src/snoopi.jl
test/runtests.jl
test/snoopr.jl

Also provide infrastructure analyze and explain these invalidations.
This is WIP and could break any time. But here's a demo (must be run on https://github.com/JuliaLang/julia/pull/35768):
```julia
julia> using SnoopCompile
julia> invalidations = @snoopr using FixedPointNumbers
1159-element Array{Any,1}:
MethodInstance for reduce_empty(::Base.BottomRF{typeof(max)}, ::Type{VersionNumber})
1
MethodInstance for reduce_empty_iter(::Base.BottomRF{typeof(max)}, ::Set{VersionNumber}, ::Base.HasEltype)
2
MethodInstance for reduce_empty_iter(::Base.BottomRF{typeof(max)}, ::Set{VersionNumber})
3
MethodInstance for foldl_impl(::Base.BottomRF{typeof(max)}, ::NamedTuple{(),Tuple{}}, ::Set{VersionNumber})
4
MethodInstance for mapfoldl_impl(::typeof(identity), ::typeof(max), ::NamedTuple{(),Tuple{}}, …
```

snoopr ("snoop recompilations") to detect method invalidations

---

.travis.yml
Project.toml
docs/src/reference.md
docs/src/snoopr.md
src/invalidations.jl
test/snoopr.jl

This makes it easy to find the source of a specific problem triggered by invalidation. Motivated by investigating https://github.com/JuliaLang/julia/issues/36005.

Add `findcaller` and improve docs

---

docs/src/snoopr.md
examples/invalidations_blog.jl
src/invalidations.jl
test/snoopr.jl

This is just housekeeping, but having good and consistent names is a big aid to understanding, so let's do this now before the invalidations work gets publicized.

A few cleanups

---

Project.toml
SnoopCompileAnalysis/Project.toml
SnoopCompileBot/Project.toml
SnoopCompileBot/src/snoop_bench.jl
SnoopCompileBot/src/snoop_bot.jl
SnoopCompileBot/test/runtests.jl
SnoopCompileCore/Project.toml
test/runtests.jl

Fixes the bot on 1.6. Tested against MusicXML v0.3.2. I had to delete the `exhausive` keywords from the snoop scripts; that was never in a released version of SnoopCompile, so that isn't cheating.
@aminya, one thing I had to do to make it work was execute the instructions in https://github.com/timholy/SnoopCompile.jl/issues/105#issuecomment-649345931 in the MusicXML environment, since the bot launches with `--project`. Interestingly, I had to manually edit the paths in the resulting `MusicXML/Manifest.toml` manually: doing the `rm SnoopCompileCore ...` deleted the `path=` statement from the Manifest.toml and reverted to the git tree sha.

Version 1.6.2

---

Project.toml
SnoopCompileAnalysis/Project.toml
SnoopCompileAnalysis/src/invalidations.jl
SnoopCompileBot/Project.toml
SnoopCompileCore/Project.toml
docs/src/snoopr.md
src/SnoopCompile.jl
test/snoopr.jl
utils/dev.jl
utils/register.jl

This is the final tool (so far) for fixing invalidations. `ascend` makes it much easier to identify a fruitful place to intervene and fix inference problems.
This also adds tools for bumping the versions across-the-board. What do you think of this, @aminya? Overall I think our best strategy is to keep all version numbers in lock-step, and that's the workflow made easy with these tools. When you want to bump the version, you say `bump_version(v"1.7.0")`. After the PR merges, update your local master branch to the latest, check out a branch of `registries/General`, and then `register_all()`. Then submit your `registries/General` as a PR.

Add support for Cthulhu

---

docs/make.jl
docs/src/snoopr.md

For some reason the docs haven't deployed since 1.5. [This run](https://github.com/timholy/SnoopCompile.jl/runs/824519353) suggests, if anything, that it's due to a lack of `push_preview` (though that seems weird). Let's try this, though, and see if it fixes it.

Try to get the docs deploying

---

src/invalidations.jl
test/snoopr.jl

Core.Compiler is protected from genuine invalidation, so any apparent invalidations are basically irrelevant.

Exclude methods from Core.Compiler by default

---

src/SnoopCompile.jl

This centralizes all snoopr decision-making. If one goes to the trouble to backport the necessary infrastructure to older Julia versions, this makes it easier to load the functionality.

Make the version check more flexible

---

docs/src/snoopi.md
docs/src/snoopr.md

This goes into detail about why some precompilation directives are only partially successful, and illustrates what can be done to fix them. It also urges users to think twice before reaching immediately for automated tools (`SnoopCompile.parcel` or the bot) to generate lists of precompile directives. I often find that I get much better results from manual inspection and intervention, but our documentation has really emphasized the automated tools.

Expand discussion of precompilation and its limitations

---

SnoopCompileBot/Project.toml
SnoopCompileBot/README.md
SnoopCompileBot/src/SnoopCompileBot.jl

This deprecates SnoopCompileBot in favor of CompileBot. 
Because SnoopCopmileBot was in a sub-directory of this repository, changing the URL is not possible due to git limitations. I decided to rename the package.
I would appreciate it if you can merge this and register a new version for SnoopCompileBot. Then, remove the directory when the registration is done.
https://github.com/JuliaRegistries/General/pull/22253
https://github.com/JuliaRegistries/General/pull/19557
https://github.com/JuliaRegistries/General/pull/21615

Deprecate SnoopCompileBot in favor of CompileBot

---

.github/workflows/ci.yml
Project.toml
src/parcel_snoopc.jl
test/runtests.jl

This looks for the `var` syntax and also decouples the test from JLD, since any package might change and break the test.

Fix isdefined check on nightly

---

test/snoopi.jl
test/testmodules/FuncKinds.jl

I'm not sure which change broke this, but I suspect it's changes in `repr` module-scoping, adding `Main` in front of more things which then get excluded. This is a more typical test set anyway, so this is probably a good change in any case.
The `@eval`s are necessary to trigger a fresh entrance into inference.

Fix tests on nightly

---

src/parcel_snoopi_deep.jl

The `def` field of `Core.MethodInstance` is typed as
`Union{Method,Module}`. Consequently, we should not assume that it's
a `Method`.
Unfortunately I've not been able to come up with a simple test
that fails without this change, though I have seen failures
in real-world usage.

snoopi_deep: check that mi.def is a Method

---

test/snoopi_deep.jl

One of the tests relies on the two fastest-to-infer MethodInstances
having a difference in their inference times. However, in rare cases
they can "tie." Just skip this portion of the tests when this happens.

Fix a rare test failure in snoopi_deep

---

src/parcel_snoopi.jl
test/snoopi.jl

Based on poking around Julia's `src/dump.c`, it's my understanding
that a *disconnected* (backedge-free) `MethodInstance` needs to be
cached in the module owning the `Method`.
The implication is that Base methods that get called on
package-defined objects cannot be cached on their own merits, so we
should exclude such `MethodInstance`s.
The way to fix this is to make such calls inferrable,
in which case they will be cached in the package module thanks to
their backedges.

Require method ownership

---

test/snoopi_deep.jl

The fix in #155 was incomplete, this should do it.

Don't leave the flamegraph headless in tests

---

src/parcel_snoopi_deep.jl

Move method instance's specTypes Type Tuple from a compile-time argument
to a runtime argument, to prevent compiling a specialization for every
_value_ in the data!
I hadn't meant to write it that way in the first place, I had just done
it absent-mindedly, because `specTypes` is a Type, so I hadn't thought
about moving it back into the value domain.
We used `@snoopi_deep` to find out the problem and fix this performance
problem! It's neat to see it profiling itself! :tada:
Fixes https://github.com/timholy/SnoopCompile.jl/issues/150.

Dramatically improve `flamegraph(timing)` performance

---

src/SnoopCompile.jl
src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

This analysis tool is useful to detect methods that get a crazy number
of specializations. These are candidates for refactoring into smaller,
more independent chunks or nospecialize annotations.

Add accumulate_by_method

---

.github/workflows/ci.yml
Project.toml
SnoopCompileCore/src/SnoopCompileCore.jl
SnoopCompileCore/src/snoopl.jl
src/SnoopCompile.jl
src/parcel_snoopl.jl
test/runtests.jl
test/snoopl.jl

This uses the associated code added in https://github.com/JuliaLang/julia/pull/37136 to get its timings.
Adds a macro to SnoopCompileCore, `@snoopl`, which collects timings for the LLVM optimization of compilation, and adds functions to display and understand the resulting timings.
Co-Authored-By: @Sacha0 @vchuravy

Add snoopl() to snoop time in LLVM optimization

---

test/snoopr.jl

Starting with https://github.com/JuliaLang/julia/pull/38608,
MethodInstances are printed with module-qualifiers.

Qualify MethodInstances in tests

---

Project.toml
src/parcel_snoopi.jl
src/parcel_snoopi_deep.jl
src/write.jl
test/snoopi_deep.jl
test/testmodules/SnoopBench.jl

This is the analog of our previous functionality for `@snoopi_deep`. It works by finding the root-most frame in each branch that owns the method being called and which can `eval` all the types in the signature. 
In most respects this probably replaces #157, and really should probably replace the `parcel`/`write` style when using `@snoopi`; that seems to have nothing but disadvantages compared to this PR. (But it's still young, so let's give it a little while to mature before we think about clearing out cruft.)

Add parcel for snoopi_deep

---

src/parcel_snoopi_deep.jl
src/visualizations.jl

This allows one to optionally consolidate information about
inference with different Const values to their base MethodInstance.
It also adds a convenience method for visualizing directly from the
timing data.

Option to consolidate consts in inference timing

---

src/parcel_snoopi.jl
src/parcel_snoopi_deep.jl
test/snoopi.jl
test/snoopi_deep.jl

This allows:
- excluding specific modules, forcing it to choose a deeper call for the root
- is more consistent about time: now it's consistent about MethodInstances
(dropping the Consts, which are not precompilable) and keeping the longest
time for that MethodInstance.
- allow a tmin parameter to suppress branches that drop below a threshold
inclusive time

Improve parcel for deep

---

src/SnoopCompile.jl
src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

This adds a lot of exports, but the analysis of the callees and callers at breaks
in inference chains is fairly complicated. These utilities streamline the analysis.
This requires https://github.com/JuliaLang/julia/pull/38566

Add `inference_triggers`

---

src/SnoopCompile.jl
src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

`build_inclusive_timing` is really just a constructor for
`InclusiveTiming` objects, so we might as well spell it that way.
It's also clearly useful as an exported entity.

Export InclusiveTiming and its constructor

---

src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

When analyzing the overhead of specialization, sometimes you want
to distinguish the first run (or first run with concrete signature)
from later runs. Consequently it can be useful to extract the
flattened times in the order in which inference happened.
This also switches to a depth-first algorithm for searching the graph,
as required to support `sorted=false`.

Allow `flatten_times` to return unsorted

---

src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

It's natural to hope to collect inference triggers in just
a child node, but these are not preserved (for good reason).
At least we should throw an explanatory error.

More informative error for child-node itrigs

---

src/SnoopCompile.jl
src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

When identifying the caller of an inference-triggering callee,
sometimes it's nice to skip over higher order functions.
For instance in a `do`-block, you might prefer to attribute
any inference trigger in the anonymous function to the parent
scope that implemented the `do`-block rather than the
higher-order function used by the `do`-statement.

Skip higher-order funcs for inference triggers

---

test/snoopi_deep.jl

It's hard to count on the fact that the exclusive time will be ordered
in a specific way. This reorganizes some tests to exploit the unsorted
output of `flatten_times` to make it more robust.

Make tests more robust to timing order

---

Project.toml
docs/src/snoopr.md
src/SnoopCompile.jl
src/deep_demos.jl
src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

This provides integration with Cthulhu's `ascend`, making it
significantly easier to analyze inference triggers.
The docstrings had also gotten out of date, and this updates them
while also allowing more compact docstrings by moving definitions to a
set of demos.
Finally, this adds an "orientation" docstring to SnoopCompile itself.
These can be helpful in orienting users to the API.

`ascend` integration and docs cleanup

---

src/parcel_snoopi.jl
src/parcel_snoopi_deep.jl
test/snoopi.jl
test/snoopi_deep.jl

This gets `known_type` out of the business of `eval`ing type names and
uses the internal machinery instead.

Improve accuracy & speed of known_type

---

Project.toml
SnoopCompileCore/src/snoopi_deep.jl
src/SnoopCompile.jl
src/deep_demos.jl
src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

This modifies `@snoopi_deep` to return "normalized" data that allows all analyses to have access to both inclusive and exclusive time. It also converts all times to `secs::Float64`. Finally, it does a full refresh on all the docstrings to account for the changes in results and their display.
Supersedes and closes #180. Other than #190 and the documenter docs, this is the last change I expect before the big release.
CC @Sacha0.

snoopi_deep: return inclusive & exclusive times

---

docs/src/snoopi_deep_analysis.md
docs/src/snoopr.md
src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

There are useful things one can do with the full InferenceTimingNode,
so it makes sense to keep it.

Store full InferenceTimingNode in InferenceTrigger

---

src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

Long runs can take a long time to do instruction-pointer lookup.
However, since we only credit the "self" time there is no need to
look up everything. This limits the lookup to the triggering instruction
pointer. It also attributes the cost to the whole "inlining chain."

PGDO: lookup only self time

---

docs/src/snoopi_deep_analysis.md

This typo made me search some dictionaries for "warmpup" - I'm not a native English speaker 😉

fix typo warmpup

---

examples/OptimizeMe.jl
src/parcel_snoopi.jl
src/parcel_snoopi_deep.jl
test/snoopi_deep.jl
test/testmodules/SnoopBench.jl

These are things I fixed while using this in practice. Unfortunately I don't have tests for them (bad, bad), I guess when I encountered them in practice I felt it was important to keep moving.
Better to have them than not, I think.

A grabbag of random fixes

---

src/parcel_snoopi.jl
test/snoopi.jl
test/testmodules/A.jl

Fix and test Varargs

---

src/parcel_snoopi_deep.jl

The former implementation collected some "spurious" invalidations:
methods in `Core` (which runs in an old world-age) and precompiled
CodeInstances (which get loaded from cache with max_world = 0).
This also returns the full InferenceTimingNodes, which seems useful
since it gives a sense of the cost of recompiling it.

Improve selectivity in "deep" invalidations

---

docs/src/reference.md
docs/src/snoopi_deep.md
src/SnoopCompile.jl
src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

This is a more accurate description of what it does, and therefore
is less likely to cause confusion. This also reworks the implementation
to make it easier to run the core logic on either MethodInstances or
InferenceTimingNodes.

Rename sanity-checker to `staleinstances`

---

docs/src/snoopr.md
src/invalidations.jl
test/snoopr.jl

This allows one to find all invalidations that affect a
particular package.

Invalidations: support recursive filtermod

---

docs/src/snoopr.md
src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

Detect slots or ssavalues that are `Core.Box` and warn the user.
Note this applies to the entire method, not just the line triggering inference.
Comment: originally this had a different title & commit message. It was a weird VSCode bug.

Detect Core.Box (#226)

---

src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

Sometimes multiple inference triggers occur on the same
source-code line, and it's better to keep them separated by callee.

Segregate loctrigs by callee

---

src/invalidations.jl

BTW, I'm not sure why the `umis =` part is there (the docstring doesn't refer to it).

Fix indentation in uinvalidated docstring

---

src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

This was discovered in the process of putting together the demo in https://github.com/aviatesk/JET.jl/issues/105. JET is an interesting comparison for this package because in principle it's more thorough than SnoopCompile, so it would be great to get both packages to the point where they can be compared.

Fix a Union-handling bug in `hascorebox`

---

test/snoopr.jl

This was deprecated a while ago but I had never noticed.

Fix instance->methodinstance depwarn

---

docs/src/reference.md

I just noticed that `@snoopl` isn't in the documentation at all. I know it's not very widely used, but it'd be nice to refer to it here at least. :)
`@snoopl` was originally added in https://github.com/timholy/SnoopCompile.jl/pull/135/.

Add `@snoopl` to reference docs

---

src/parcel_snoopi_deep.jl

The issue here is a call to
hvcat(rows::Tuple{Vararg{Int}}, xs::_DenseConcatGroup...) = Base.typed_hvcat(promote_eltype(xs...), rows, xs...)
which has a couple of `Core._apply_iterate` and the matching fails
when it doesn't match the trigger `promote_eltype`.
I tried to come up with a MWE but failed.
Fixes #244

Suggest only if the callee matches the trigger

---

docs/src/index.md
docs/src/pgdsgui.md
docs/src/snoopi_deep.md
docs/src/snoopi_deep_analysis.md
docs/src/snoopi_deep_parcel.md
docs/src/snoopr.md
docs/src/tutorial.md

While reading through the documentation, I found some words might look
nicer if they are codified (i.e. by enclosing them by backticks), mainly:
- make sure to codify `MethodInstance`
- if a package module is actually used, codify its name, e.g. `SnoopCompile`
Please tell me if you don't like these changes -- I don't mind simply
reverting that part.
Unrelated to above changes, I also added some typo fixes.

minor documentation improvements

---

Project.toml
SnoopCompileCore/Project.toml
src/invalidations.jl
test/colortypes.jl
test/snoopr.jl

Fixes `MethodError: no method matching getroot(::Nothing)` when constructing invalidation trees from certain patterns. Detected with packages in an intermediate state in the refactoring around IrrationalConstants.jl of StatsFuns.jl and LogExpFunctions.jl.
CC @ChrisRackauckas

Fix tree construction with method overwriting

---

SnoopCompileCore/src/snoopi_deep.jl
src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

It's often convenient to be able to easily find the parent.

Make InferenceTimingNode bidirectional

---

test/snoopi_deep.jl

I failed to notice the failure on 1.6

Fix a test failure

---

src/invalidations.jl
test/snoopi_deep.jl
test/testmodules/Stale/Project.toml
test/testmodules/Stale/StaleA/Project.toml
test/testmodules/Stale/StaleA/src/StaleA.jl
test/testmodules/Stale/StaleB/Project.toml
test/testmodules/Stale/StaleB/src/StaleB.jl
test/testmodules/Stale/StaleC/Project.toml
test/testmodules/Stale/StaleC/src/StaleC.jl

These were printed to the console but not otherwise stored.
Storing them allows one to give them more emphasis and perform
analysis. With https://github.com/JuliaLang/julia/pull/41913,
it becomes possible to attribute them to specific method
definitions or deletions. (Of course there might be multiple
reasons, but we need to identify at least one in order to make
progress.)
CC @chriselrod, @vtjnash, @ChrisRackauckas. If anyone plans to try this, until 2.8 is released be sure to `dev SnoopCompileCore` too as it is a separate (subdir) module and there are changes due to #257.

Track invalidations during deserialization

---

src/invalidations.jl
test/snoopi_deep.jl
test/snoopr.jl
test/testmodules/Stale/Manifest.toml

Improves on #260 by collecting all callees and callers and then doing
the attribution at once (finding at least one identifiable callee).

Improve attribution of delayed invalidations

---

src/SnoopCompile.jl
src/invalidation_and_inference.jl
src/invalidations.jl
src/parcel_snoopi_deep.jl
test/snoopi_deep.jl

This allows one to identify the particular invalidations that block
precompilation of particular MethodInstances.
I am not 100% sure this is right. In particular, it might be too conservative; maybe one should `SnoopCompile.getrroot(hits[i])` to see the real impact? But I checked whether the root CodeInstances are there in the precompile cache, and they seem to be. So my best guess is that this is painting an accurate picture as-is. I might let this sit on master for a few days before making a release. 
CC @ChrisRackauckas. It seems to suggest that invalidation is not your first-order problem with https://github.com/SciML/ModelingToolkit.jl/pull/1215, as you seemed to expect. But I wanted to get this tool out there in some form.

Identify invalidating blockers of precompilation

---

.github/workflows/Documenter.yml
Project.toml
SnoopCompileCore/Project.toml
docs/src/index.md
docs/src/reference.md
docs/src/snoopi.md
docs/src/snoopi_deep.md
docs/src/snoopi_deep_analysis.md
docs/src/snoopi_deep_parcel.md
docs/src/snoopr.md
src/invalidation_and_inference.jl

This updates the documentation (the main goal was to get `precompile_blockers` in, but other fixes were made too). A more thorough "cookbook" revision of the documentation may need to wait until later.
Also bumps version to 2.8.0.

Update docs, v2.8.0

---

Project.toml
SnoopCompileCore/Project.toml
src/visualizations.jl

Detect stray clicks in pgdsgui

---

docs/src/snoopi.md
docs/src/snoopi_deep_parcel.md
src/parcel_snoopi.jl
src/parcel_snoopi_deep.jl
test/snoopi.jl
test/snoopi_deep.jl
test/testmodules/SnoopBench.jl

If a package only supports Julia versions that have `Base.bodyfunction`,
we don't need to define `__lookup_kwbody__`.
However, we can't simply query the running version of Julia,
because the precompile file may used by a different Julia version.
This adds a manual keyword argument.

Slim precompile files for Julia 1.6+

---

test/snoopi_deep.jl

Formerly this seemed to return a single MethodInstance, but now it
returns two. The change may be from improvements to MethodAnalysis,
likely https://github.com/timholy/MethodAnalysis.jl/pull/27.
The new behavior is certainly the correct one (there are two distinct
methods, so there had better be two MethodInstances with that
signature---even though one will never get another CodeInstance).

Fix MethodInstance multiplicity

---

src/invalidations.jl
test/snoopi_deep.jl

This updates both code and tests for the precompilation changes in
https://github.com/JuliaLang/julia/pull/43990. Most urgently, a new
invalidation location tag, "jl_insert_method_instance", was added, and
analysis will error unless fixed. There are also subtle changes in
attribution that require small changes elsewhere.

Update for julia#43990

---

.github/workflows/ci.yml
SnoopPrecompile/LICENSE
SnoopPrecompile/Project.toml
SnoopPrecompile/README.md
SnoopPrecompile/src/SnoopPrecompile.jl
SnoopPrecompile/test/SnoopPC_A/Project.toml
SnoopPrecompile/test/SnoopPC_A/src/SnoopPC_A.jl
SnoopPrecompile/test/SnoopPC_B/Project.toml
SnoopPrecompile/test/SnoopPC_B/src/SnoopPC_B.jl
SnoopPrecompile/test/runtests.jl
docs/make.jl
docs/src/index.md
docs/src/snoop_pc.md

This small package makes it easy to exhaustively precompile on
Julia 1.8 and higher. In brief, your package should look like
```julia
module MyPackage
using SnoopPrecompile
let
@precompile_calls begin
end
end
end # module MyPackage
```
There are also facilities for "setup" code, see the documentation
for details.

Add SnoopPrecompile package

---

README.md

`SnoopPrecompile.jl` is not yet visible in the stable docs because `SnoopCompile.jl` hasn't been updated after the addition of `SnoopPrecompile.jl`. Long story short, probably best to refer people to the dev docs by default. If agreeing with this change, then don't forget to update the link in the top-right at the GitHub repository too.

Link to dev documentation by default

---

SnoopPrecompile/Project.toml
SnoopPrecompile/src/SnoopPrecompile.jl
SnoopPrecompile/test/SnoopPC_A/src/SnoopPC_A.jl

Fixes
```
ERROR: LoadError: UndefVarError: SnoopPrecompile not defined
Stacktrace:
[1] macro expansion
@ ~/.julia/packages/SnoopPrecompile/bsz6N/src/SnoopPrecompile.jl:71 [inlined]
[2] macro expansion
[...]
```
when loading the module via `using SnoopPrecompile: @precompile_setup, @precompile_all_calls`.

Fix undefined `SnoopPrecompile`

---

docs/src/snoop_pc.md

I think `all_begin` was intended to be `begin`? 
The former errorred for me when I tried to add it to a package.

fix typo in SnoopPrecompile docs

---

src/invalidations.jl
test/snoopi_deep.jl
test/snoopr.jl

Julia-1.8 reports invalidations slightly differently from previous
versions. This harmonizes the output and avoids duplicating
trees/roots/branches.
While this suffices to fix SnoopCompile on 1.8, nightly will require additional work (failure anticipated).

Implement more powerful tree-join, fix tests on Julia-1.8

---

Project.toml
src/parcel_snoopi_deep.jl

AbstractTrees has historically been included indirectly, but this package has
long added new methods to AbstractTrees functions. In retrospect, this was probably
a poor decision. In addition to updating compat, this makes AbstractTrees an
explicit dependency.

Update to FlameGraphs 1.0

---

src/invalidations.jl
src/parcel_snoopi_deep.jl
test/snoopr.jl
test/testmodules/Invalidation/Manifest.toml
test/testmodules/Invalidation/PkgC/Project.toml
test/testmodules/Invalidation/PkgC/src/PkgC.jl
test/testmodules/Invalidation/PkgD/Manifest.toml
test/testmodules/Invalidation/PkgD/Project.toml
test/testmodules/Invalidation/PkgD/src/PkgD.jl
test/testmodules/Invalidation/Project.toml

"Delayed" invalidations occur during package loading in response to some event that happened before
the package was loaded. Because the trigger is separated in time from its consequences, we did not formerly have a mechanism to clearly attribute these to a cause. Julia 1.9 has recently added more logging to make this more robust; this PR updates SnoopCompile to take advantage of the new information.
Fixes the confusing output mentioned in https://github.com/timholy/SnoopCompile.jl/issues/296#issuecomment-1245562684 (CC @joa-quim).

Fix attribution of "delayed" invalidations

---

Project.toml
SnoopPrecompile/test/runtests.jl
src/invalidations.jl

This updates to the logging format used by the most recent nightly build
of Julia (1.9). While there has been a lot of churn in this area, there
are reasons to hope that we're entering a period of stability: there are
no known "holes" in our coverage after resolving the `invoke` issues
(https://github.com/JuliaLang/julia/pull/46010 and fixup PRs that came
later), and the subsequent major rewrite of the invalidation logic
(https://github.com/JuliaLang/julia/pull/46920) suggests this format may
have some durability.
CC @vtjnash

Update invalidation logging format

---

src/parcel_snoopi_deep.jl

https://github.com/JuliaLang/julia/pull/46608 gave rise to a warning during precompilation of SnoopCompile:
```jl
julia> using SnoopCompile
[ Info: Precompiling SnoopCompile [aa65fe97-06da-5843-b5b1-d5d13cad87d2]
WARNING: method definition for precompilable_time at /home/tchr/.julia/packages/SnoopCompile/J3dtR/src/parcel_snoopi_deep.jl:290 declares type variable T but does not use it.
```

Fix warning during precompilation

---

SnoopPrecompile/src/SnoopPrecompile.jl
SnoopPrecompile/test/SnoopPC_C/Project.toml
SnoopPrecompile/test/SnoopPC_C/src/SnoopPC_C.jl
SnoopPrecompile/test/runtests.jl

@timholy, the added test breaks on `1.0.2` and not on `1.0.1`.
So I've reverted the changes of `1.0.2` and we can start working on a fix.
I'm not sure if the precompilation scenario is valid code in `RecipesBase` (this is clearly a niche involving meta-programming), and I'd be happy to change some - considered invalid - but working statements in https://github.com/JuliaPlots/Plots.jl/blob/master/RecipesBase/src/RecipesBase.jl#L600-L619.

revert broken commit - add test

---

SnoopPrecompile/test/runtests.jl
src/invalidations.jl
test/snoopi_deep.jl
test/snoopr.jl
test/testmodules/Invalidation/Manifest.toml

We only need to clear the table between packges, and only the integer keys are ambiguous.
Fixes the [bug reported on discourse](https://discourse.julialang.org/t/julia-v1-9-0-beta2-is-fast/92290/26?u=tim.holy)

 Clear backedge_table less eagerly

---

docs/src/tutorial.md

As much as details are nice, sometimes giving something that's easy to copy/repeat is good. Maybe this could be added as a library function (it probably would need to be a macro).

Add a copy-paste invalidations analysis script

---

src/parcel_snoopi_deep.jl

See https://github.com/timholy/SnoopCompile.jl/pull/212#discussion_r1062926193.

Don't error on empty typeinf flamegraph; print a warning instead

---

docs/src/jet.md
docs/src/snoopr.md
src/invalidations.jl
src/parcel_snoopc.jl
src/parcel_snoopi_deep.jl
test/snoopr.jl

Picked up as the source of hanging in the doctests. Also updates doctests to reduce the number of errors.

Fix a hang in `uinvalidated`

---

Project.toml
src/SnoopCompile.jl
src/invalidations.jl
src/report_invalidations.jl
test/snoopr.jl

Hello 👋🏻! There has been a lot of activity around hunting down invalidations lately, for example:
- [julia-invalidations](https://github.com/julia-actions/julia-invalidations)
- [discourse thread](https://discourse.julialang.org/t/potential-performance-regressions-in-julia-1-8-for-special-un-precompiled-type-dispatches-and-how-to-fix-them/86359)
- [SciML issue](https://github.com/SciML/DifferentialEquations.jl/issues/786)
As mentioned in [this comment](https://discourse.julialang.org/t/potential-performance-regressions-in-julia-1-8-for-special-un-precompiled-type-dispatches-and-how-to-fix-them/86359/21) of the `discourse thread`, I've added a function called `report_invalidations` to [ReportMetrics.jl](https://github.com/CliMA/ReportMetrics.jl) which summarizes the output of …

Add `report_invalidations` to tabulate invalidations summary

---

SnoopCompileCore/src/snoopl.jl

It's common to use projects and load libraries not in the base environment, or possibly ones with different versions.

Use active project for `snoopl`

---

src/invalidations.jl

Skip empty sublists with no actual invalidations

---

src/invalidations.jl
test/snoopi_deep.jl
test/testmodules/Stale/StaleB/src/StaleB.jl

These were incorrectly assigned to mt_backedges.
Fixes #357

Target verify_methods to backedges

---

test/runtests.jl

With Julia 1.6, a precompile statement is generated:
```julia
julia> using SnoopCompile
julia> logfile = joinpath(tempdir(), "anon.log")
"/tmp/anon.log"
julia> @snoopc logfile begin
map(x->x^2, [1,2,3])
end
Launching new julia process to run commands...
done.
julia> data = SnoopCompile.read(logfile)
(UInt64[0x00000000003d57dc, 0x00000000003d590b, 0x00000000016f8738], ["Tuple{Type{Base.Generator{I, F} where F where I}, Main.var\"#1#2\", Array{Int64, 1}}", "Tuple{typeof(Base.map), Function, Array{Int64, 1}}", "Tuple{typeof(Base.collect_similar), Array{Int64, 1}, Base.Generator{Array{Int64, 1}, Main.var\"#1#2\"}}"])
julia> read(logfile, String) |> println
4020491	"Tuple{typeof(Base.map), Function, Array{Int64, 1}}"
4020188	"Tuple{Type{Base.Generator{I, F} where F where I}, Main.var"#1#2", …
```

Fix snoopc test

---

Project.toml
docs/src/jet.md
docs/src/snoopi.md
docs/src/snoopi_deep_analysis.md
ext/CthulhuExt.jl
ext/JETExt.jl
src/SnoopCompile.jl
src/invalidations.jl
src/parcel_snoopi_deep.jl
test/runtests.jl
test/snoopi_deep.jl

This is a continuation of https://github.com/timholy/SnoopCompile.jl/pull/376 for Cthulhu.jl after https://github.com/timholy/SnoopCompile.jl/pull/379

Make Cthulhu.jl a weakdep, implement CthulhuExt.jl

---

docs/src/index.md
docs/src/snoopc.md

I noticed that they still say that native code isn't cached.

Update the docs to mention that native code is now cached

---

docs/src/explanations/tools.md

fix docs typo

---

docs/src/tutorials/snoop_inference.md

Without this it's common to get truncation because the default is 5.
And discoverability isn't great because `AbstractTrees.print_tree` isn't documented https://juliacollections.github.io/AbstractTrees.jl/stable/search/?q=print_tree
but has a docstring that shows this arg https://github.com/JuliaCollections/AbstractTrees.jl/blob/af3fabd36631efe361bc8e1ba45f9b84e898b459/src/printing.jl#L17

Docs: add `maxdepth=100` arg to print_tree

---

docs/src/tutorials/snoop_inference.md

This provides some hints for handling constant propagation (CC @SimonDanisch). It also fixes some inconsistencies in timing as reported on slack by @kshyatt.

Docs: add material on constprop

---

docs/src/tutorials/pgdsgui.md
ext/SCPyPlotExt.jl
src/SnoopCompile.jl

The `SCPyPlotExt` had three problems:
- the default argument to `pdata` is `Profile.fetch()`, but `Profile` was not imported
- the extension was not adding methods to `SnoopCompile.pgdsgui`
- `prep_ri` was failing with `UndefVarError: lookup_firstip! not defined`
As a result, the tutorial on `pgdsgui` was broken.
This commit fixes these issues. In the process, I also fixed syntax highlighing in a couple of places in the documentation.

Fix SCPyPlotExt

---

.github/workflows/ci.yml
src/parcel_snoop_inference.jl

Fix InterpreterIP reference

---

src/utils.jl
test/snoop_inference.jl

Add back `methods_with_generators` (fix #407)

---

docs/src/tutorials/snoop_llvm.md
src/parcel_snoop_llvm.jl

Some of the `Dicts` in `llvm_yaml` had entries `"before" => nothing`,
and that was breaking parsing.
Fixes #405

llvm parsing: filter out `nothing`

---

Project.toml
src/utils.jl
src/write.jl
test/snoop_inference.jl

`SnoopCompile.write(filename, data; suppress_time=true)` now omits the
timing information. Closes #314.
~~If #413 can be resolved quickly, it would be ideal to make another 3.0.x release before merging this.~~ nvm, that ended up being a test-only fix.

Add option to make write more git diff-friendly

---

docs/src/reference.md
docs/src/tutorials/snoop_inference.md
docs/src/tutorials/snoop_inference_parcel.md
src/parcel_snoop_inference.jl
src/utils.jl

This also enhances its implementation to make it more flexible.
Closes #411

Add docs for `isprecompilable`

---

src/invalidations.jl

There seem to be rare cases where edge invalidations tagged with
`"verify_method"` do not list their cause. This adds a fallback target
to store such invalidations.
Also fixes an issue with the ordering of insertions that triggered an
assert. CC @LilithHafner

Handle untracked causes of invalidation

---

.github/workflows/Documenter.yml
.github/workflows/ci.yml
Project.toml
SnoopCompileCore/src/SnoopCompileCore.jl
SnoopCompileCore/src/snoop_inference.jl
docs/src/tutorials/invalidations.md
src/SnoopCompile.jl
src/inference_demos.jl
src/parcel_snoop_inference.jl
src/utils.jl
test/extensions/jet.jl
test/runtests.jl
test/snoop_inference.jl
test/testmodules/Invalidation/Project.toml
test/testmodules/Stale/Project.toml

This leverages the [new timing fields of `CodeInstance`](https://github.com/JuliaLang/julia/pull/57074) to replace the old `Core.Compiler.Timings` module. There is a bit of loss particularly in the domain of constant-propagation, which is illustrated in https://gist.github.com/timholy/9a64b27c1932bb414e69b8fe48284b5e. (Read `testcase.jl` before looking at the results.) As a consequence there are a small handful of failing tests locally, but the vast majority pass.
This requires https://github.com/JuliaLang/julia/pull/58124 or alternatively (with some modification to this PR) https://github.com/JuliaLang/julia/pull/58123.

Update `@snoop_inference` for Julia 1.12

---

.github/workflows/Documenter.yml

'min' is not yet available. Long-term, we want 'min', but the documentation has never built in the JuliaDebug host, so we need at least one build to go through.
Fixes #433

Build docs with 'pre'
